### ISSUE TITLE
videoentity_load() collides with hook_load() provided by the node module?

### ISSUE THREAD

**Issue by chrissnyder2337** [Lullabot/entity-api-demos#2]
Im not sure where to leave questions:

I noticed that in videoentity.module `videoentity_load()` is defined as the "Menu Autoloader". How does this function not collide with `hook_load()` provided by the core node module? or is that the intention? Wouldn't this function be called every time any node is loaded?

Thank you in advance :)

Cheers,
Chris Snyder

**Comment by blakehall** [comment]
Hi Chris.

If you take a look at the `hook_load()` docs at https://api.drupal.org/api/drupal/modules%21node%21node.api.php/function/hook_load/7

"This is a node-type-specific hook, which is invoked _only for the node type being affected_. See Node API hooks for more information."

Which is to say `hook_load` only fires for the particular content type module that defines a node type. As long as there isn't a content (node) type provided by the videoentity module there won't be any conflicts using this hook.
